language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js:
  - "8"
  - "9"

script:
  - npm i 
  - npm test

after_script:
  - npm install coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js